In [1]:
import pandas as pd
import joblib

In [2]:
#carregar o modelo de regressão linear
modelo_lr = joblib.load('../modelo/modelo_regressao_linear.pkl')

In [4]:
novos_imoveis = pd.read_csv('../data/predict/novos_imoveis.csv')
novos_imoveis.head()

,area,bedrooms,bathrooms,stories,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,parking,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,5000,3,2,2,1,0,1,0,1,2,1,1,0
1,6200,4,3,2,1,1,1,0,1,2,1,0,0
2,3500,2,1,1,0,0,0,0,0,1,0,0,1
3,7200,4,3,2,1,0,1,1,1,3,1,1,0
4,4100,3,2,1,0,0,0,0,1,1,0,0,1

In [8]:
# Refazer a ordem das colunas para corresponder ao modelo
novos_imoveis = novos_imoveis[modelo_lr.feature_names_in_]

In [9]:
# Prever os preços dos novos imóveis
previsoes = modelo_lr.predict(novos_imoveis)
print(previsoes)

[ 7176345.6813739   8989223.58931931  2552598.80890497  9776192.33771536
  4656830.31520796 12020143.72109982  2411017.52618013  7317926.96409873
  9036417.35022758  5085174.84257592]

In [18]:
# Adicionar as previsões ao DataFrame
previsoes_novos_imoveis = pd.DataFrame(previsoes, columns=['preco_previsto'])
previsoes_novos_imoveis = previsoes_novos_imoveis["preco_previsto"].astype(int)

In [19]:
previsoes_novos_imoveis.head()

0    7176345
1    8989223
2    2552598
3    9776192
4    4656830
Name: preco_previsto, dtype: int64

In [22]:
# adicionar as previsões ao DataFrame original
novos_imoveis.loc[:,'preco_previsto'] = previsoes_novos_imoveis
novos_imoveis.head()

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,preco_previsto
0,5000.0,3.0,2.0,2.0,2.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,7176345.0
1,6200.0,4.0,3.0,2.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,8989223.0
2,3500.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2552598.0
3,7200.0,4.0,3.0,2.0,3.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,9776192.0
4,4100.0,3.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4656830.0

In [23]:
# Salvando o dataframe com as previsões em um novo arquivo CSV
novos_imoveis.to_csv('../data/predict/previsoes_imoveis.csv', index=False)